### ISSUE TITLE
Render error on zkoss 9.5.0 jakarta and java 17

### ISSUE THREAD

**Issue by RickSpider** [zkoss/zkcalendar#17]
Failed to mount: cells[k] is undefined
Failed to mount: this._itemsData is undefined

The calendar does not render properly or hangs when the time passes 13:00. I'm using ZK 9.5.0 Jakarta version with Java 17.

![imagen](https://github.com/user-attachments/assets/3efeb41d-cd5e-4eb4-8cb6-44c0170042e2)

**Comment by hawkchen** [comment]
Could provide more details in https://tracker.zkoss.org/browse/ZKCAL-125 e.g. zk calendar version. Since I cannot reproduce the same error.
I saw you added one item on 11/5, what's the begin and end time?

**Comment by RickSpider** [comment]
yes mi data is begin 2024-11-04 11:00:00 and end 2024-11-04 13:00:00 this error only in jakarta zkoss ee, i use last version zcal 3.12 on java 17 and zkoss ee 9.6.5 jakarta (sorry my error in zkoss version), The calendar version works correctly in Java (not Jakarta) and in ZKoss (non-Jakarta).

**Comment by hawkchen** [comment]
There is a similar bug https://tracker.zkoss.org/browse/ZKCAL-124
but I cannot reproduce the same error message as you mentioned. Besides, zkcalendar doesn't use any javax specific API, so it should be no difference between java EE and jakarta EE.
Could you please try to apply the js patch https://tracker.zkoss.org/secure/attachment/27210/zkcal-124.js in your environment to see if it eliminates your error?

See [How to Include a JavaScript file](https://www.zkoss.org/wiki/ZK_Developer%27s_Reference/How_to_get_Efficient_Support#How_to_Include_a_JavaScript_file)

**Comment by RickSpider** [comment]
Hola aplique el parche que me pasaste, y funciono correctamente, el unico problema es que si begin y end son exactamente iguales hay un vuelve el error pero eso lo soluciono sumando un segundo, no hay problemas luego de eso, muchas gracias...

**Comment by RickSpider** [comment]
Hi, I applied the patch you sent me and it worked correctly. The only problem is that if begin and end are exactly the same, the error returns, but I solved that by adding a second. There are no problems after that. Thank you very much...
