### ISSUE TITLE
Item update event problem

### ISSUE THREAD

**Issue by JBarrioL** [zkoss/zkcalendar#4]
_This event is triggered when a user drags to change a calendar item's time span_
The problem is the end time, its being wwrongfully calculated in the 3.0.0 version
if you try it in https://www.zkoss.org/zkdemo/zk_calendar/zk_calendar and go for the day option and create an item and try to edit its time span it will cut 30 mins from the new timespan.
This can be corrected with code after the event is fired, the problem is that when you drag and increment just 30 min the event wont even fire.
![Image 1](https://user-images.githubusercontent.com/23723941/113140745-1c3ce780-9229-11eb-8192-58a386082268.png)
![Image 2](https://user-images.githubusercontent.com/23723941/113140843-3d9dd380-9229-11eb-9d24-1a6655eb4ffa.png)
This is a problem given you cant drag only to add 30 min to an existing item, and the 2.1.5 version has the numberformatexception.

**Comment by cor3000** [comment]
thanks for reporting this, we'll look into it

**Comment by cor3000** [comment]
bug is tracked in our JIRA under [ZKCAL-85](https://tracker.zkoss.org/browse/ZKCAL-85)
we'll continue there

**Comment by cor3000** [comment]
fixed in version 3.0.1
